### PR TITLE
Rename "pooling" to "polling".

### LINKED ISSUE #19: pooling vs. polling
Hi, I noticed that your config has a "pooling" option.
Shouldn't this be "polling"?

### PR DESCRIPTION
**Pull request by noplanman**
Also rename "pul" to "poll".
Fixes #19

### CODE REVIEW

**Comment by noplanman** [comment]
@kosmodrey How can I properly test?
Using travis, I've set up the TEST_TELEBOT_TOKEN and TEST_TELEBOT_USER variables, but most tests fail with:
```
✖ bot.sendAction Promise rejected with: { ok: false,
error_code: 400,
description: 'Bad Request: chat not found' }
```

[link to the test](https://travis-ci.org/noplanman/telebot/builds/156936075)

**Comment by kosmodrey** [comment]
Something wrong with Travis. Local tests passed.

**Comment by kosmodrey** [comment]
Yep, master is green. Thank you for contribution :+1:

**Comment by noplanman** [comment]
You're welcome! This is my first node.js contribution 🎉 

How would I run the tests locally?

(I'm totally new to node.js)

**Comment by kosmodrey** [comment]
`TEST_TELEBOT_TOKEN` and `TEST_TELEBOT_USER` are environment variables.

Set it in cmd (Windows) with command: `set TEST_TELEBOT_TOKEN=...` 

`TEST_TELEBOT_USER` is your Telegram user id. You can check it when bot receives message from you:

```js
const TeleBot = require('telebot');
const bot = new TeleBot('-PASTEYOURTELEGRAMBOTAPITOKENHERE-');

// On every type of message
bot.on('*', msg => {
  const id = msg.from.id;
  return bot.sendMessage(id, `Your Telegram ID: ${ id }`);
});

bot.connect();
```

Send some message to bot and it will return your id.

> This is my first node.js contribution :tada:

Congratulations!

**Comment by noplanman** [comment]
Yes, that's exactly what I did, but how do I run the unit tests? The ones in the "test" folder.

**Comment by kosmodrey** [comment]
First do `npm install` and then `npm test`.

**Comment by noplanman** [comment]
Perfect, thanks! What a noob I am 😊

**Comment by noplanman** [comment]
I also get the errors locally:
```
12 passed
 8 failed
13 rejections
```

8x (for each method)
```
n. bot.<method>
Promise rejected with: { ok: false,
  error_code: 400,
  description: 'Bad Request: chat not found' }
```

13x
```
n. Unhandled Rejection
   {"ok":false,"error_code":400,"description":"Bad Request: chat not found","type":"rejection","file":"test/index.js"}
```

Is there anything else I need to set up first?
I deleted the webhook to make sure that's not the issue.

Thanks for your help

**Comment by kosmodrey** [comment]
Can you check if the tests fails on older commits, before your PR? I can't reproduce this.

**Comment by noplanman** [comment]
All clear, had the wrong value in the `TEST_TELEBOT_USER` variable, sorry.

It's working now 👍 

Will update the travis env too, which should make it work as well.

**Pull request merged**
